baseURL = "https://pandulceworld.netlify.app/"
disqusShortname = ""
languageCode = "en-us"
paginate = "3"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Pan Dulce World!"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "Packages"
name = "Packages"
weight = 2
[[menu.main]]
URL = "tools"
name = "Packages"
weight = 2
[[menu.main]]
URL = "author"
name = "The Team"
weight = ""
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "/"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "This is meta description"
google_tag_manager = ""
home = "Home"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Welcome to Pan Dulce World!<br> Where it's what's inside that counts :)"
[params.cookies]
enable = true
expire_days = 2
[params.cta]
description = "Receive a box of freshly baked pan dulce delivered twice per month. "
enable = true
image = "images/hugo-muscot.svg"
title = "Subscribe to a box"
[params.cta.button]
enable = true
label = "Subscribe"
link = "https://pandulceworld.netlify.app/tools/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
